# -*- coding: utf-8 -*-
"""TextAnalyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1stDtSCk39qLuQzeLIZMBnDTNJGErOQor
"""

pip install textblob nltk

import re
from collections import Counter
from textblob import TextBlob
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords',quiet=True)
nltk.download('punkt',quiet=True)

class TextAnalyzer:
    def __init__(self, text):
        self.text = text
        self.blob = TextBlob(text)
    def get_word_count(self):
        words = self.text.split()
        return len(words)
    def get_sentiment(self):
        score = self.blob.sentiment.polarity
        if score > 0:
            return "Positive"
        elif score < 0:
            return "Negative"
        else:
            return "Neutral"
    def get_keywords(self):
        cleaned_text = re.sub(r'[^\w\s]', '', self.text).lower()
        words = cleaned_text.split()
        stop_words = set(stopwords.words('english'))
        filtered_words = [word for word in words if word not in stop_words]
        return Counter(filtered_words).most_common(3)
user_input = input("Enter text: ")
analyzer = TextAnalyzer(user_input)
print("Word Count:", analyzer.get_word_count())
print("Sentiment:", analyzer.get_sentiment())
print("Top Keywords:", analyzer.get_keywords())